# Generated by Django 5.2.4 on 2025-07-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_move', models.CharField(max_length=10)),
                ('computer_move', models.CharField(max_length=10)),
                ('winner', models.CharField(max_length=10)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
